import { Inter } from 'next/font/google'
import { ConfigProvider } from "antd";
import './globals.css'
import './responsive.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} page`}>
      <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: "#22292E",
              // Alias Token
              colorBgContainer: "#ffffff",
            },
          }}
        >
          <div>
            {children}
          </div>
        </ConfigProvider>
        </body>
    </html>
  )
}
